# Check Sundials installation
FILE(GLOB_RECURSE SUNDIALS_FOUND_CMAKE_FILE "${SUNDIALS_INSTALL_PATH}/SUNDIALSConfig.cmake")

MESSAGE(STATUS "Sundials install path : ${SUNDIALS_INSTALL_PATH}")
MESSAGE(STATUS "Sundials found cmake config : ${SUNDIALS_FOUND_CMAKE_FILE}")

IF (SUNDIALS_FOUND_CMAKE_FILE)
  INCLUDE(${SUNDIALS_FOUND_CMAKE_FILE})
ELSE()
  MESSAGE(FATAL_ERROR "-- Sundials is not found at ${SUNDIALS_INSTALL_PATH}")
ENDIF()
